### ISSUE TITLE
training script

### ISSUE THREAD

**Issue by fzuqxt** [hahazh/OFR-BRN#3]
Hello author, I use zoomingslowmo framework training script has a gradient error problem, I would like to ask if you can provide the overall framework file？

**Comment by hahazh** [comment]
We have trained this code multiple times and used it for other related tasks, but did not find the problem you mentioned. Perhaps you can provide the detailed error report.

**Comment by fzuqxt** [comment]
/home/iv/miniconda3/envs/stvsr/lib/python3.8/site-packages/torch/optim/lr_scheduler.py:131: UserWarning: Detected call of `lr_scheduler.step()` before `optimizer.step()`. In PyTorch 1.1.0 and later, you should call them in the opposite order: `optimizer.step()` before `lr_scheduler.step()`.  Failure to do this will result in PyTorch skipping the first value of the learning rate schedule. See more details at https://pytorch.org/docs/stable/optim.html#how-to-adjust-learning-rate
  warnings.warn("Detected call of `lr_scheduler.step()` before `optimizer.step()`. "
/home/iv/miniconda3/envs/stvsr/lib/python3.8/site-packages/torch/functional.py:568: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at  /opt/conda/conda-bld/pytorch_1646755903507/work/aten/src/ATen/native/TensorShape.cpp:2228.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
/home/iv/miniconda3/envs/stvsr/lib/python3.8/site-packages/torch/nn/functional.py:1944: UserWarning: nn.functional.sigmoid is deprecated. Use torch.sigmoid instead.
  warnings.warn("nn.functional.sigmoid is deprecated. Use torch.sigmoid instead.")
Traceback (most recent call last):
  File "train.py", line 196, in <module>
    main()
  File "train.py", line 162, in main
    model.optimize_parameters(current_step)
  File "/mnt/Temp_new/QXT/OFR-BRN-master/src/models/VideoSR_base_model.py", line 103, in optimize_parameters
    l_pix.backward()
  File "/home/iv/miniconda3/envs/stvsr/lib/python3.8/site-packages/torch/_tensor.py", line 363, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
  File "/home/iv/miniconda3/envs/stvsr/lib/python3.8/site-packages/torch/autograd/__init__.py", line 173, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation: [torch.cuda.FloatTensor [16, 2, 32, 32]], which is output 0 of AsStridedBackward0, is at version 3; expected version 2 instead. Hint: enable anomaly detection to find the operation that failed to compute its gradient, with torch.autograd.set_detect_anomaly(True)

**Comment by hahazh** [comment]
This could be due to a version issue with PyTorch. In certain versions, inplace operations can result in some computation nodes being overwritten, preventing the computation graph from being backpropagated. There are various solutions to this problem, and you can refer to this resource for more information:  https://zhuanlan.zhihu.com/p/582536685

**Comment by fzuqxt** [comment]
你好作者,我使用您链接里的方法,返回的错误是/home/iv/miniconda3/envs/stvsr/lib/python3.8/site-packages/torch/autograd/__init__.py:173: UserWarning: Error detected in CudnnGridSamplerBackward0. Traceback of forward call that caused the error:
  File "train.py", line 179, in <module>
    main()
  File "train.py", line 147, in main
    trainer.train_one_sample(train_data, current_step)
  File "/mnt/Temp_new/QXT/RSTT-main/tools/Trainer.py", line 72, in train_one_sample
    self.outputs = self.model(self.inputs)
  File "/home/iv/miniconda3/envs/stvsr/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/iv/miniconda3/envs/stvsr/lib/python3.8/site-packages/torch/nn/parallel/data_parallel.py", line 166, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/home/iv/miniconda3/envs/stvsr/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/mnt/Temp_new/QXT/RSTT-main/models/OFR_BRN.py", line 83, in forward
    flows_forward, flows_backward, flow_out_forward_half, flow_out_backward_half = self.compute_biflow(lrs)
  File "/mnt/Temp_new/QXT/RSTT-main/models/OFR_BRN.py", line 73, in compute_biflow
    flows_forward[:, i, :, :, :] = flow_warp(flows_forward[:, i, :, :, :], flow_out_forward_half[:, i, :, :, :].permute(0, 2, 3, 1))
  File "/mnt/Temp_new/QXT/RSTT-main/models/general_module.py", line 199, in flow_warp
    output = F.grid_sample(
  File "/home/iv/miniconda3/envs/stvsr/lib/python3.8/site-packages/torch/nn/functional.py", line 4201, in grid_sample
    return torch.grid_sampler(input, grid, mode_enum, padding_mode_enum, align_corners)
 (Triggered internally at  /opt/conda/conda-bld/pytorch_1646755903507/work/torch/csrc/autograd/python_anomaly_mode.cpp:104.)
  Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
Traceback (most recent call last):
  File "train.py", line 179, in <module>
    main()
  File "train.py", line 147, in main
    trainer.train_one_sample(train_data, current_step)
  File "/mnt/Temp_new/QXT/RSTT-main/tools/Trainer.py", line 74, in train_one_sample
    loss.backward()
  File "/home/iv/miniconda3/envs/stvsr/lib/python3.8/site-packages/torch/_tensor.py", line 363, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
  File "/home/iv/miniconda3/envs/stvsr/lib/python3.8/site-packages/torch/autograd/__init__.py", line 173, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation: [torch.cuda.FloatTensor [5, 2, 64, 64]], which is output 0 of AsStridedBackward0, is at version 3; expected version 2 instead. Hint: the backtrace further above shows the operation that failed to compute its gradient. The variable in question was changed in there or anywhere later. Good luck!

**Comment by fzuqxt** [comment]
Could you please send me your complete training program file? I am very interested in your work, and your work is very good! Thank you very much.
